# Generated by Django 3.2.7 on 2022-07-01 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(choices=[(0, 'Подтверждение почты'), (1, 'Восстановление пароля')])),
                ('last_email_dt', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
