# Generated by Django 3.2.7 on 2022-07-01 13:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('boat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(0, 'Ожидание подтверждения'), (-1, 'Отменено'), (1, 'Подтверждено'), (2, 'Ожидание предоплаты'), (3, 'Активно'), (4, 'Завершено')], default=0)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('total_sum', models.DecimalField(decimal_places=2, max_digits=8)),
                ('boat', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='boat.boat')),
            ],
        ),
        migrations.CreateModel(
            name='Prepayment',
            fields=[
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='booking.booking')),
                ('until', models.DateTimeField()),
            ],
        ),
    ]
