# Generated by Django 3.2.7 on 2022-07-30 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_booking_spec'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='spec',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
