# Generated by Django 3.2.7 on 2022-08-18 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_alter_booking_spec'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
