repos:
-   repo: local
    hooks:
    -   id: flake8
        name: flake8
        entry: flake8
        args: ["--config=setup.cfg"]
        language: python
        types: [python]

    -   id: coverage
        name: coverage
        entry: coverage
        args: ["run manage.py test -v 2"]
        language: python
        types: [python]