repos:
-   repo: local # exclude: tests/|migrations/ args: [--config, .flake8] repo: https://github.com/pycqa/flake8 rev: '5.0.4'
    hooks:
    -   id: flake8
        name: flake8
        entry: flake8
        args: ["--config=setup.cfg"]
        language: python
        types: [python]