# Generated by Django 3.2.7 on 2022-07-01 13:10

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import file.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Base',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('lon', models.DecimalField(decimal_places=6, max_digits=9)),
                ('lat', models.DecimalField(decimal_places=6, max_digits=9)),
                ('address', models.TextField()),
                ('state', models.CharField(db_index=True, max_length=255)),
                ('website', models.URLField(blank=True, max_length=255, null=True)),
                ('phone', models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.RegexValidator(code='invalid_phone', message='Номер телефона должен содержать 10 цифр', regex='(\\d+){10}')])),
            ],
        ),
        migrations.CreateModel(
            name='BaseImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=file.utils.get_file_path)),
                ('base', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='base.base')),
            ],
        ),
    ]
