# Generated by Django 3.2.7 on 2022-07-03 08:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boat', '0003_alter_boat_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boat',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='boats', to='boat.model'),
        ),
    ]
