# Generated by Django 3.2.7 on 2022-07-07 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boat', '0004_alter_boat_model'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='boat',
            options={'permissions': [('view_boats_on_moderation', 'Can view boats on moderation'), ('moderate_boats', 'Can moderate boats'), ('view_my_boats', 'Can view my boats')]},
        ),
    ]
