# Generated by Django 3.2.7 on 2022-07-21 08:39

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boat', '0008_alter_tariff_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tariff',
            options={'verbose_name': 'Тариф', 'verbose_name_plural': 'Тарифы'},
        ),
        migrations.AddField(
            model_name='tariff',
            name='weight',
            field=models.IntegerField(default=1, help_text='Рассчитывается автоматически', verbose_name='Приоритет тарифа'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tariff',
            name='boat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tariffs', to='boat.boat', verbose_name='Лодка'),
        ),
        migrations.AlterField(
            model_name='tariff',
            name='duration',
            field=models.IntegerField(help_text='Напр.: неделя - 7, выходные - 3, сутки - 1', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Продолжительность'),
        ),
        migrations.AlterField(
            model_name='tariff',
            name='end_date',
            field=models.DateField(verbose_name='Окончание'),
        ),
        migrations.AlterField(
            model_name='tariff',
            name='fri',
            field=models.BooleanField(default=False, verbose_name='Пт.'),
        ),
        migrations.AlterField(
            model_name='tariff',
            name='max',
            field=models.IntegerField(blank=True, help_text='Максимальное кол-во аренд подряд. Пусто - нет ограничения', null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Максимум'),
        ),
        migrations.AlterField(
            model_name='tariff',
            name='min',
            field=models.IntegerField(help_text='Минимальное кол-во аренд подряд', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Минимум'),
        ),
        migrations.AlterField(
            model_name='tariff',
            name='mon',
            field=models.BooleanField(default=False, verbose_name='Пн.'),
        ),
        migrations.AlterField(
            model_name='tariff',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='tariff',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='tariff',
            name='sat',
            field=models.BooleanField(default=False, verbose_name='Сб.'),
        ),
        migrations.AlterField(
            model_name='tariff',
            name='start_date',
            field=models.DateField(verbose_name='Начало'),
        ),
        migrations.AlterField(
            model_name='tariff',
            name='sun',
            field=models.BooleanField(default=False, verbose_name='Вс.'),
        ),
        migrations.AlterField(
            model_name='tariff',
            name='thu',
            field=models.BooleanField(default=False, verbose_name='Чт.'),
        ),
        migrations.AlterField(
            model_name='tariff',
            name='tue',
            field=models.BooleanField(default=False, verbose_name='Вт.'),
        ),
        migrations.AlterField(
            model_name='tariff',
            name='wed',
            field=models.BooleanField(default=False, verbose_name='Ср.'),
        ),
    ]
