# Generated by Django 3.2.7 on 2022-07-26 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boat', '0013_auto_20220726_1100'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tariff',
            options={'ordering': ['start_date', 'end_date', '-weight'], 'verbose_name': 'Тариф', 'verbose_name_plural': 'Тарифы'},
        ),
        migrations.RemoveField(
            model_name='tariff',
            name='duration_display',
        ),
    ]
