# Generated by Django 3.2.7 on 2022-07-01 13:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chat', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('booking', '0002_booking_renter'),
        ('boat', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='recipient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='messages_as_recipient', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='message',
            name='sender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='messages_as_sender', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='messagebooking',
            name='booking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='messages', to='booking.booking'),
        ),
        migrations.AddField(
            model_name='messageboat',
            name='boat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='messages', to='boat.boat'),
        ),
    ]
