# Generated by Django 3.2.7 on 2022-08-19 06:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_rename_content_booking_term_content'),
        ('chat', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagebooking',
            name='booking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='booking.booking'),
        ),
    ]
