# Generated by Django 3.2.7 on 2022-07-30 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_booking_renter'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='spec',
            field=models.JSONField(default=''),
            preserve_default=False,
        ),
    ]
