# Generated by Django 3.2.7 on 2022-08-25 07:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('boat', '0024_alter_boat_base'),
        ('base', '0001_initial'),
        ('booking', '0006_rename_content_booking_term_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoatInfo',
            fields=[
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='boat_info', serialize=False, to='booking.booking')),
                ('prepayment_required', models.BooleanField(blank=True, null=True)),
                ('term_content', models.TextField(blank=True, null=True)),
                ('type', models.IntegerField(blank=True, choices=[(0, 'Парусная яхта'), (1, 'Катер/моторная лодка'), (2, 'Лодка'), (3, 'Гулет'), (4, 'Гидроцикл'), (5, 'Моторная яхта'), (6, 'Хаусбот'), (7, 'Катамаран'), (8, 'Тримаран')], null=True)),
                ('photo', models.ImageField(upload_to='')),
                ('spec', models.JSONField(blank=True, null=True)),
                ('base', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='base.base')),
                ('model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='boat.model')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='requests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='booking',
            name='term_content',
        ),
        migrations.CreateModel(
            name='BoatInfoCoordinates',
            fields=[
                ('booking_boat', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='coordinates', serialize=False, to='booking.boatinfo')),
                ('lon', models.DecimalField(decimal_places=6, max_digits=9)),
                ('lat', models.DecimalField(decimal_places=6, max_digits=9)),
                ('address', models.TextField()),
                ('state', models.CharField(db_index=True, max_length=255)),
            ],
        ),
    ]
