# Generated by Django 3.2.7 on 2022-08-25 09:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boat', '0024_alter_boat_base'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('booking', '0010_auto_20220825_1100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boatinfo',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='boat.model'),
        ),
        migrations.AlterField(
            model_name='boatinfo',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requests', to='user.user'),
        ),
        migrations.AlterField(
            model_name='boatinfo',
            name='prepayment_required',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='boatinfo',
            name='type',
            field=models.IntegerField(choices=[(0, 'Парусная яхта'), (1, 'Катер/моторная лодка'), (2, 'Лодка'), (3, 'Гулет'), (4, 'Гидроцикл'), (5, 'Моторная яхта'), (6, 'Хаусбот'), (7, 'Катамаран'), (8, 'Тримаран')]),
        ),
    ]
