# Generated by Django 3.2.7 on 2022-08-16 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_user_email_notification'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('view_support', 'Can view support'), ('support_chat', 'Can support chat'), ('view_all_bookings', 'Can view all bookings')], 'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.AlterField(
            model_name='user',
            name='email_notification',
            field=models.BooleanField(default=False, help_text='О смене статуса лодки, бронирования.', verbose_name='По электронной почте'),
        ),
    ]
