# Generated by Django 3.2.7 on 2022-08-18 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_auto_20220816_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email_notification',
            field=models.BooleanField(default=True, help_text='О смене статуса лодки, бронирования.', verbose_name='По электронной почте'),
        ),
    ]
