# Generated by Django 3.2.7 on 2022-07-01 13:10

import boat.models
from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Boat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('text', models.TextField(blank=True, null=True)),
                ('status', models.IntegerField(choices=[(-2, 'Удалена'), (-1, 'Отклонена'), (0, 'Сохранена'), (1, 'На проверке'), (2, 'Опубликована')], default=0)),
                ('issue_year', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2999)])),
                ('length', models.DecimalField(decimal_places=1, max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('0.1'))])),
                ('width', models.DecimalField(decimal_places=1, max_digits=3, validators=[django.core.validators.MinValueValidator(Decimal('0.1'))])),
                ('draft', models.DecimalField(decimal_places=1, max_digits=2, validators=[django.core.validators.MinValueValidator(Decimal('0.1'))])),
                ('capacity', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(99)])),
                ('type', models.IntegerField(choices=[(0, 'Парусная яхта'), (1, 'Катер/моторная лодка'), (2, 'Лодка'), (3, 'Гулет'), (4, 'Гидроцикл'), (5, 'Моторная яхта'), (6, 'Хаусбот'), (7, 'Катамаран'), (8, 'Тримаран')])),
                ('prepayment_required', models.BooleanField(default=False)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'permissions': [('can_view_boats_on_moderation', 'Can view boats on moderation'), ('can_moderate_boats', 'Can moderate boats')],
            },
        ),
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BoatCoordinates',
            fields=[
                ('boat', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='coordinates', serialize=False, to='boat.boat')),
                ('lon', models.DecimalField(decimal_places=6, max_digits=9)),
                ('lat', models.DecimalField(decimal_places=6, max_digits=9)),
                ('address', models.TextField()),
                ('state', models.CharField(db_index=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ComfortBoat',
            fields=[
                ('boat', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='comfort_boat', serialize=False, to='boat.boat')),
                ('berth_amount', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(99)])),
                ('cabin_amount', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(99)])),
                ('bathroom_amount', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(9)])),
            ],
        ),
        migrations.CreateModel(
            name='MotorBoat',
            fields=[
                ('boat', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='motor_boat', serialize=False, to='boat.boat')),
                ('motor_amount', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(9)])),
                ('motor_power', models.DecimalField(decimal_places=1, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.1'))])),
            ],
        ),
        migrations.CreateModel(
            name='Specification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('сategory', models.IntegerField(choices=[(0, 'Прочее'), (1, 'Электроника')])),
                ('boat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specifications', to='boat.boat')),
            ],
        ),
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='models', to='boat.manufacturer')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BoatPricePeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('boat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices_period', to='boat.boat')),
            ],
        ),
        migrations.CreateModel(
            name='BoatPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(choices=[(0, 'Сутки')], default=0)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('boat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='boat.boat')),
            ],
            options={
                'ordering': ['start_date', 'end_date'],
            },
        ),
        migrations.CreateModel(
            name='BoatFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(upload_to=boat.models.get_upload_to)),
                ('boat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='boat.boat')),
            ],
        ),
        migrations.CreateModel(
            name='BoatFav',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('boat', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='favs', to='boat.boat')),
            ],
        ),
    ]
