# Generated by Django 3.2.7 on 2022-07-01 13:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('boat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='boatfav',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fav_boats', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='boat',
            name='base',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='boats', to='base.base'),
        ),
        migrations.AddField(
            model_name='boat',
            name='model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='boats', to='boat.model'),
        ),
        migrations.AddField(
            model_name='boat',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boats', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='boatfav',
            unique_together={('boat', 'user')},
        ),
    ]
