# Generated by Django 3.2.7 on 2022-07-01 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boat', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='boat',
            options={'permissions': [('view_boats_on_moderation', 'Can view boats on moderation'), ('moderate_boats', 'Can moderate boats')]},
        ),
    ]
