# Generated by Django 3.2.7 on 2022-07-21 07:53

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boat', '0006_auto_20220707_2247'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tariff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('name', models.CharField(max_length=255)),
                ('duration', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('min', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('max', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('mon', models.BooleanField(default=False)),
                ('tue', models.BooleanField(default=False)),
                ('wed', models.BooleanField(default=False)),
                ('thu', models.BooleanField(default=False)),
                ('fri', models.BooleanField(default=False)),
                ('sat', models.BooleanField(default=False)),
                ('sun', models.BooleanField(default=False)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('boat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tariffs', to='boat.boat')),
            ],
        ),
    ]
