# Generated by Django 3.2.7 on 2022-07-21 07:59

from decimal import Decimal

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boat', '0007_tariff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tariff',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
    ]
