# Generated by Django 3.2.7 on 2022-07-22 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boat', '0009_auto_20220721_1139'),
    ]

    operations = [
        migrations.AddField(
            model_name='tariff',
            name='active',
            field=models.BooleanField(default=False, verbose_name='Активен'),
        ),
        migrations.AlterField(
            model_name='tariff',
            name='weight',
            field=models.IntegerField(help_text='Рассчитывается автоматически', verbose_name='Вес тарифа'),
        ),
    ]
