# Generated by Django 3.2.7 on 2022-07-24 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boat', '0010_auto_20220722_1126'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tariff',
            name='max',
        ),
    ]
