# Generated by Django 3.2.7 on 2022-07-26 08:00

from django.db import migrations


def update_tariffs(apps, schema_editor): # pragma: no cover
    Tariff = apps.get_model('boat', 'Tariff')
    for tariff in Tariff.objects.all():
        tariff.save()

class Migration(migrations.Migration):

    dependencies = [
        ('boat', '0012_tariff_duration_display'),
    ]

    operations = [
        migrations.RunPython(update_tariffs),
    ]
