# Generated by Django 3.2.7 on 2022-07-26 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boat', '0014_auto_20220726_1151'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boatpriceperiod',
            name='boat',
        ),
        migrations.DeleteModel(
            name='BoatPrice',
        ),
        migrations.DeleteModel(
            name='BoatPricePeriod',
        ),
    ]
