# Generated by Django 3.2.7 on 2022-07-26 21:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boat', '0015_auto_20220726_1401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tariff',
            name='duration',
            field=models.IntegerField(help_text='Напр.: неделя - 7, выходные - 3, сутки - 1', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Продолжительность, дней'),
        ),
        migrations.AlterField(
            model_name='tariff',
            name='end_date',
            field=models.DateField(verbose_name='Окончание действия'),
        ),
        migrations.AlterField(
            model_name='tariff',
            name='min',
            field=models.IntegerField(help_text='Минимальный срок аренды', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Минимальный срок аренды'),
        ),
        migrations.AlterField(
            model_name='tariff',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название тарифа'),
        ),
        migrations.AlterField(
            model_name='tariff',
            name='start_date',
            field=models.DateField(verbose_name='Начало действия'),
        ),
    ]
