# Generated by Django 3.2.7 on 2022-08-18 08:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('boat', '0020_termtemplate'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TermTemplate',
            new_name='Term',
        ),
        migrations.AddField(
            model_name='boat',
            name='term',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='boats', to='boat.term'),
        ),
    ]
