# Generated by Django 3.2.7 on 2022-08-18 09:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boat', '0022_auto_20220818_1141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boat',
            name='term',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='boats', to='boat.term'),
        ),
    ]
