# Generated by Django 3.2.7 on 2022-07-01 14:15

from django.db import migrations

def create_groups(apps, schema_editor):
    Group       = apps.get_model('auth', 'Group')
    Permission  = apps.get_model('auth', 'Permission')
    
    group, _ = Group.objects.get_or_create(name='boat_owner')
    perms = Permission.objects.filter(name__in=['add_boat', 'change_boat', 'view_boat', 'delete_boat'])
    for p in perms:
        group.permissions.add(p)

    group, _ = Group.objects.get_or_create(name='boat_moderator')
    perms = Permission.objects.filter(name__in=['view_boats_on_moderation', 'moderate_boats'])
    for p in perms:
        group.permissions.add(p)

class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_groups)
    ]
