# Generated by Django 3.2.7 on 2022-08-08 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20220727_2109'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('view_support', 'Can view support')], 'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
    ]
