# Generated by Django 3.2.7 on 2022-08-08 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_user_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('view_support', 'Can view support'), ('support_chat', 'Can support chat')], 'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
    ]
