# Generated by Django 3.2.7 on 2022-08-16 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_user_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_notification',
            field=models.BooleanField(default=False),
        ),
    ]
