# Generated by Django 3.2.7 on 2022-09-07 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_auto_20220818_1111'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='use_dark_theme',
            field=models.BooleanField(default=False, verbose_name='Использовать тёмную тему'),
        ),
    ]
